spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
  mail:
    username: ${SMTP_USER_NAME}
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${SMTP_USER_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
azure:
  host:
    uri: ${AZURE_HOST}
  adb2c:
    openid:
      configuration:
        url: ''
    tenant:
      name: ${AZURE_TENANT_NAME}
      token:
        validation:
          url: ''
        scope: openid
        grant:
          type: password
      id: ${AZURE_TENANT_ID}
    client:
      secret: ${WEB_SECRET_ID}
    application:
      id: ${WEB_CLIENT_ID}
    redirect:
        uri: ${WEB_REDIRECT_URI}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
microsoft:
  graph:
    scope: https://graph.microsoft.com/.default